// flow-typed signature: 7380f93a5a854a5bddc16908554bd7b8
// flow-typed version: <<STUB>>/babel-preset-flow_v^6.23.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-flow/lib/index-compiled' {
  declare module.exports: any;
}

declare module 'babel-preset-flow/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-flow/lib/index-compiled.js' {
  declare module.exports: $Exports<'babel-preset-flow/lib/index-compiled'>;
}
declare module 'babel-preset-flow/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-flow/lib/index'>;
}
