// flow-typed signature: 47772d0f4b2ffe3e96bce24ed77992ac
// flow-typed version: <<STUB>>/brackets-eslint_v^3.0.6/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'brackets-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'brackets-eslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'brackets-eslint/dist/log' {
  declare module.exports: any;
}

declare module 'brackets-eslint/dist/main' {
  declare module.exports: any;
}

declare module 'brackets-eslint/dist/node/domain' {
  declare module.exports: any;
}

declare module 'brackets-eslint/dist/node/eslint' {
  declare module.exports: any;
}

declare module 'brackets-eslint/dist/types' {
  declare module.exports: any;
}

declare module 'brackets-eslint/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'brackets-eslint/dist/log.js' {
  declare module.exports: $Exports<'brackets-eslint/dist/log'>;
}
declare module 'brackets-eslint/dist/main.js' {
  declare module.exports: $Exports<'brackets-eslint/dist/main'>;
}
declare module 'brackets-eslint/dist/node/domain.js' {
  declare module.exports: $Exports<'brackets-eslint/dist/node/domain'>;
}
declare module 'brackets-eslint/dist/node/eslint.js' {
  declare module.exports: $Exports<'brackets-eslint/dist/node/eslint'>;
}
declare module 'brackets-eslint/dist/types.js' {
  declare module.exports: $Exports<'brackets-eslint/dist/types'>;
}
declare module 'brackets-eslint/main.js' {
  declare module.exports: $Exports<'brackets-eslint/main'>;
}
