// flow-typed signature: d03b3402c519d0eb4661e2cc35f41d37
// flow-typed version: <<STUB>>/os_v^0.1.1/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'os'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'os' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'os/index' {
  declare module.exports: $Exports<'os'>;
}
declare module 'os/index.js' {
  declare module.exports: $Exports<'os'>;
}
