// flow-typed signature: cd60af9134c6a2ae0b2b1336e52b659a
// flow-typed version: <<STUB>>/react-firebase_v^2.2.5/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-firebase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-firebase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-firebase/connect' {
  declare module.exports: any;
}

declare module 'react-firebase/Provider' {
  declare module.exports: any;
}

declare module 'react-firebase/umd' {
  declare module.exports: any;
}

declare module 'react-firebase/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-firebase/connect.js' {
  declare module.exports: $Exports<'react-firebase/connect'>;
}
declare module 'react-firebase/index' {
  declare module.exports: $Exports<'react-firebase'>;
}
declare module 'react-firebase/index.js' {
  declare module.exports: $Exports<'react-firebase'>;
}
declare module 'react-firebase/Provider.js' {
  declare module.exports: $Exports<'react-firebase/Provider'>;
}
declare module 'react-firebase/umd.js' {
  declare module.exports: $Exports<'react-firebase/umd'>;
}
declare module 'react-firebase/utils.js' {
  declare module.exports: $Exports<'react-firebase/utils'>;
}
